-- ===========================================================================
-- wsb-dd MySQL schema
--
-- Design goal: this tool runs on a schedule and ACCUMULATES history. Every run
-- is its own immutable batch; prior runs are never overwritten.
--
--   dd_runs            -> one row per execution (run metadata + parameters)
--   dd_ticker_mentions -> one row per (run, ticker), FK to dd_runs
--
-- Writes use INSERT ... ON DUPLICATE KEY UPDATE so re-running the SAME run_id
-- is idempotent (e.g. after a partial failure), but each new execution gets a
-- fresh run_id and therefore a fresh batch of rows.
--
-- Apply with:  mysql -u <user> -p <db> < sql/schema.sql
-- (The application also creates these via --mysql with CREATE TABLE IF NOT EXISTS.)
-- ===========================================================================

CREATE TABLE IF NOT EXISTS dd_runs (
    run_id         BIGINT       NOT NULL AUTO_INCREMENT,
    run_uuid       CHAR(36)     NOT NULL,                 -- stable id generated by the app per execution
    started_at     DATETIME     NOT NULL,                 -- UTC
    finished_at    DATETIME     NULL,                     -- UTC, set on success
    subreddit      VARCHAR(64)  NOT NULL,
    sort           VARCHAR(16)  NOT NULL,                 -- new | hot | top
    time_filter    VARCHAR(16)  NULL,                     -- day | week | month | ... (top only)
    post_limit     INT          NULL,
    min_score      INT          NOT NULL DEFAULT 0,
    flair_mode     VARCHAR(16)  NOT NULL DEFAULT 'exact', -- exact | contains
    posts_scanned  INT          NOT NULL DEFAULT 0,
    posts_matched  INT          NOT NULL DEFAULT 0,
    universe_size  INT          NULL,
    PRIMARY KEY (run_id),
    UNIQUE KEY uq_run_uuid (run_uuid),
    KEY idx_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dd_ticker_mentions (
    run_id          BIGINT      NOT NULL,
    ticker          VARCHAR(8)  NOT NULL,
    distinct_posts  INT         NOT NULL,
    total_mentions  INT         NOT NULL,
    score_weighted  BIGINT      NOT NULL,                 -- sum of post scores across distinct posts
    first_seen      DATETIME    NOT NULL,                 -- UTC, earliest post created_utc
    last_seen       DATETIME    NOT NULL,                 -- UTC, latest post created_utc
    permalinks      TEXT        NULL,                     -- space-separated source permalinks
    PRIMARY KEY (run_id, ticker),
    CONSTRAINT fk_mentions_run
        FOREIGN KEY (run_id) REFERENCES dd_runs (run_id) ON DELETE CASCADE,
    KEY idx_ticker (ticker),
    KEY idx_ticker_seen (ticker, last_seen)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Example queries
-- ---------------------------------------------------------------------------
-- Latest run's leaderboard:
--   SELECT m.* FROM dd_ticker_mentions m
--   JOIN (SELECT run_id FROM dd_runs ORDER BY started_at DESC LIMIT 1) r USING (run_id)
--   ORDER BY m.score_weighted DESC;
--
-- A ticker's trend over time:
--   SELECT r.started_at, m.distinct_posts, m.total_mentions, m.score_weighted
--   FROM dd_ticker_mentions m JOIN dd_runs r USING (run_id)
--   WHERE m.ticker = 'NVDA' ORDER BY r.started_at;
